### ISSUE TITLE
Can't install `@zoralabs/protocol-sdk` with yarn 4.x

### ISSUE THREAD

**Issue by JoshNavi** [ourzora/zora-protocol#413]
Reproductions:

With yarn v4

```sh
~~> yarn add @zoralabs/protocol-sdk
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ TypeError: @zoralabs/mints-deployments@npm:*: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at b1t (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:677:20583)
    at /Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:677:19098
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async I1 (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:147:33381)
    at async wb (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:147:31578)
    at async Object.N4 (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:147:33665)
    at async Em (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:677:21070)
    at async /Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:677:18746
    at async S1t (/Users/josh/.cache/node/corepack/yarn/4.2.2/yarn.js:677:18700)
➤ YN0000: └ Completed in 3s 127ms
➤ YN0000: · Failed with errors in 3s 144ms
```

With npm v10: was able to install

```sh
~~> npm i --save @zoralabs/protocol-sdk

added 12 packages, and audited 13 packages in 3s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by iainnash** [comment]
We have a fix that's coming out today.

**Comment by oveddan** [comment]
should be fixed with `@zoralabs/protocol-sdk` version `0.5.13`

could you please try installing the latest version?

**Comment by iainnash** [comment]
Fix is in:
```
> yarn
➤ YN0088: A new stable version of Yarn is available: 4.2.2!
➤ YN0088: Upgrade now by running yarn set version 4.2.2

➤ YN0087: Migrated your project to the latest Yarn version 🚀

➤ YN0000: · Yarn 4.2.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @zoralabs/protocol-sdk@npm:0.5.13, @zoralabs/protocol-deployments@npm:0.1.10
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ demo-protocol-sdk@workspace:. doesn't provide viem (p2a449), requested by @zoralabs/protocol-sdk.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 2 packages were added to the project (+ 7.58 MiB).
➤ YN0000: └ Completed in 0s 336ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 403ms
```

```
> yarn --version
4.2.1
```

**Comment by JoshNavi** [comment]
Confirming it works! Thank you!

**Comment by kyhyco** [comment]
Hello folks!

Running into issue with this again. Here is an example repo of not working - https://github.com/kyhyco/for-zoralabs

with yarn v4, `yarn add @zorolabs/protocol-sdk` is looking for `@zoralabs/mints-deployments`.

```bash
❯ yarn add @zoralabs/protocol-sdk
➤ YN0000: · Yarn 4.3.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ TypeError: @zoralabs/mints-deployments@npm:*: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at k1t (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:677:20583)
    at /Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:677:19098
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async B1 (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:147:33381)
    at async Ib (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:147:31578)
    at async Object.N4 (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:147:33665)
    at async ym (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:677:21070)
    at async /Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:677:18746
    at async x1t (/Users/ky.lee/tmp/test-zora2/.yarn/releases/yarn-4.3.0.cjs:677:18700)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 196ms
```

Strangely enough installing using yarn v1 and npm works fine.

**Comment by iainnash** [comment]
We’re working on a fix for this. Unfortunately it’s a pretty large change
and taking longer than we want.

**Comment by iainnash** [comment]
Hello this is now fixed :). Let us know if you run into any further issues.

**Comment by kyhyco** [comment]
confirmed that it works!
