### ISSUE TITLE
Mints-deployments install error

### ISSUE THREAD

**Issue by rubinovitz** [ourzora/zora-protocol#429]
Is mints-deployments broken? Getting this error trying to install `yarn install @zoralabs/protocol-sdk`
```
jb@MacBook-Pro-7 nook % yarn install                        
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Project validation
➤ YN0057: │ @nook/expo: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0001: │ TypeError: @zoralabs/mints-deployments@npm:*: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at k1t (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:677:20564)
    at /Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:677:19079
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async B1 (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:147:33381)
    at async Ib (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:147:31578)
    at async Object.N4 (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:147:33665)
    at async ym (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:677:21051)
    at async /Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:677:18727
    at async x1t (/Users/jb/repos/tenfold/nook/.yarn/releases/yarn-4.3.1.cjs:677:18681)
➤ YN0000: └ Completed in 3s 204ms
➤ YN0000: · Failed with errors in 3s 215ms
```

**Comment by iainnash** [comment]
We have a known yarn/npm issue with dependent packages we're trying to fix for newer versions of yarn.

This works with yarn 1.x and npm.

**Comment by rubinovitz** [comment]
Ok we have a yarn 4 monorepo so I guess we’ll download the Zora packages
and include them as packages manually 🫠

**Comment by iainnash** [comment]
Sorry about that – I'll let you know when we can fix the underlying tooling.

**Comment by iainnash** [comment]
We've fixed the underlying packages – can you try again? We've fixed our dep tree and updated the dependent versions.

**Comment by iainnash** [comment]
This is confirmed as works. Let me know if you run into issues by opening a new ticket.
