### ISSUE TITLE
Error: cannot find token

### ISSUE THREAD

**Issue by rubinovitz** [ourzora/zora-protocol#430]
The first time I run `collectorClient.mint` on a token it errors out

```
subgraph-mint-getter.ts:161 Uncaught (in promise) Error: Cannot find token
    at SubgraphMintGetter.getMintable (subgraph-mint-getter.ts:161:13)
    at async getMint (mint-queries.ts:45:20)
    at async mint (mint-client.ts:126:27)
    at async mint (zoraProtocol.tsx:137:28)
    at async handleMint (EmbedFrame.tsx:74:24)
```

Then when I click again it finds the token and is fine. 

For reference:
Token id  19 
Contract address  0xae569256caa1273aae7b1d8f161ed19cd90d67c2
Chain id 1

**Comment by rubinovitz** [comment]
I was the problem
